[project]
name = "example_package"
version = "0.2.0"
description = "A simple demo package"
authors = [{ name = "Tamas Koncz", email = "t.koncz@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
